# Generated by Django 2.2.28 on 2025-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250319_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='edited',
            field=models.IntegerField(null=True),
        ),
    ]
