# Generated by Django 2.2.28 on 2025-03-27 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0003_note_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EditedNotes',
        ),
        migrations.AddField(
            model_name='noteview',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Note'),
        ),
        migrations.AddField(
            model_name='noteview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='viewed_by',
            field=models.ManyToManyField(related_name='viewed_notes', through='rango.NoteView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='noteview',
            unique_together={('user', 'note')},
        ),
    ]
