# Generated by Django 3.2 on 2025-03-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_note_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrolls',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
