# Generated by Django 3.2 on 2025-03-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20250327_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
