# Generated by Django 2.2.28 on 2025-03-27 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0004_auto_20250327_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NoteLiked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'note')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_notes', through='rango.NoteLiked', to=settings.AUTH_USER_MODEL),
        ),
    ]
