# Generated by Django 3.2 on 2025-03-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_students_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
