# Generated by Django 2.2.28 on 2025-03-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_alter_students_profile_picture'),
        ('rango', '0004_auto_20250327_0034'),
    ]

    operations = [
    ]
